### ISSUE TITLE
Access of memory past the end of a memory buffer

### ISSUE THREAD

**Issue by gaoethan** [ros2/tlsf#5]
In the API [malloc_ex()](https://github.com/ros2/tlsf/blob/master/tlsf/src/tlsf.c#L749) [free_ex()](https://github.com/ros2/tlsf/blob/master/tlsf/src/tlsf.c#L794) [realloc_ex()](https://github.com/ros2/tlsf/blob/master/tlsf/src/tlsf.c#L867) taking address with `&tlsf->fl_bitmap` yields a singleton pointer and passing `&tlsf->fl_bitmap` to function `set_bit `which uses it as an array. This might corrupt or misinterpret adjacent memory locations. Out-of-bounds access that memory not owned by this buffer will be accessed, causing memory corruption or incorrect computations.

**Comment by gaoethan** [comment]
This repo hasn't been developed for a long time, so here to mark this issue firstly. thanks.

**Comment by mikaelarguedas** [comment]
tlsf is a third party package that we don't modify. Please report issues on the upstream repository.
Maybe a new version of this package has been released and, if so, we could consider importing a newer version

**Comment by mikaelarguedas** [comment]
actually the upstream version got it's last commit [5 years ago](https://github.com/emeryberger/Malloc-Implementations/commit/2cbecba4425f0d7f01c393503b6cccb79be9090f#diff-103a2e08243c846f9201cf22926c5a51) so I think this will not change in the near future

**Comment by gaoethan** [comment]
#https://github.com/emeryberger/Malloc-Implementations/issues/2

**Comment by mikaelarguedas** [comment]
closing as this won't be fixed in this repository
